const assert=require('node:assert/strict'),p=require('../static/plan-b-view.js');
const now=Date.parse('2026-10-06T18:00:00Z'),date='2026-10-10';
const prefs={enabled:true,threshold:60,conditions:true};
const context={zip:'90210',zone:'America/Los_Angeles',consent:true,loading:false,error:'',data:{zip:'90210',timezone:'America/Los_Angeles',fetched_at:'2026-10-06T17:30:00Z',days:[{date,status:'available',rain:75,code:63}]}};
const check=(change={},settings={})=>p.assess(date,{...structuredClone(context),...change},{...prefs,...settings},now);
assert.equal(check().eligible,true);assert.match(check().message,/75%.*60%/);
assert.equal(check({}, {enabled:false}).eligible,false);
assert.equal(check({consent:false}).eligible,false);
assert.equal(check({loading:true}).eligible,false);
assert.equal(check({error:'Unavailable'}).eligible,false);
assert.equal(check({zip:'10001'}).eligible,false);
assert.equal(check({zone:'America/New_York'}).eligible,false);
assert.equal(check({zone:'invalid'}).eligible,false);
for(const fetched_at of ['bad','2026-10-06T17:00:00Z','2026-10-06T18:01:00Z'])assert.equal(check({data:{...context.data,fetched_at}}).eligible,false);
for(const status of ['past','too_early','unavailable'])assert.equal(check({data:{...context.data,days:[{...context.data.days[0],status}]}}).eligible,false);
assert.equal(check({data:{...context.data,days:[{date:'2026-10-11',status:'available',rain:100,code:95}]}}).eligible,false);
assert.equal(check({}, {threshold:80,conditions:false}).eligible,false);
assert.equal(check({}, {threshold:0}).eligible,false);
for(const rain of [null,NaN,-1,101])assert.equal(check({data:{...context.data,days:[{date,status:'partial',rain,code:null}]}},{conditions:false}).eligible,false);
assert.equal(check({data:{...context.data,days:[{date,status:'partial',rain:null,code:95}]}}).eligible,true);
assert.equal(check({data:{...context.data,days:[{date,status:'partial',rain:null,code:999}]}}).eligible,false);
assert.equal(p.assess('2026-10-03',context,prefs,now).eligible,false);
assert.equal(p.assess('2026-11-07',context,prefs,now).eligible,false);
const original=JSON.stringify(context);check();assert.equal(JSON.stringify(context),original);
console.log('Plan B weather gates passed: opt-in, ZIP/date/timezone, exact expiry, outages, partial/unknown values, configurable triggers and immutability.');

const limits={minutes:240,budget:60,energy:'medium',count:3,include_lazy:false,weekend_date:date,day_caps:{Saturday:{Projects:1,Restaurants:1,Places:1,Activities:1},Sunday:{Projects:1,Restaurants:1,Places:1,Activities:1}}};
assert.equal(p.sameLimits(limits,structuredClone(limits)),true);
for(const [key,value] of Object.entries({minutes:120,budget:20,energy:'low',count:1,include_lazy:true,weekend_date:'2026-10-17'}))assert.equal(p.sameLimits(limits,{...limits,[key]:value}),false);
const changed=structuredClone(limits);changed.day_caps.Saturday.Places=0;assert.equal(p.sameLimits(limits,changed),false);
